# Generated by Django 5.2.11 on 2026-03-15 19:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_remove_member_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('CONTRIBUTION', 'Member Contribution'), ('LOAN_REPAY', 'Loan Repayment'), ('SAVINGS', 'Savings Deposit'), ('REVENUE', 'Revenue / Proceeds'), ('EXPENDITURE', 'Expenditure'), ('DIVIDEND', 'Dividend Payout'), ('OTHER', 'Other')], db_index=True, help_text='Financial record category. Required for aggregation and reporting.', max_length=15)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Cooperative-defined financial fields (amount_ksh, transaction_date, member, reference_number, description, etc.).')),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='core.cooperative')),
            ],
            options={
                'verbose_name': 'Financial Record',
                'db_table': 'sf_financial_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cooperative', 'category'], name='sf_financia_coopera_9fa608_idx')],
            },
        ),
        migrations.CreateModel(
            name='GovernanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_type', models.CharField(choices=[('MEETING', 'Meeting Minutes'), ('RESOLUTION', 'Resolution'), ('AUDIT', 'Audit Report'), ('CERTIFICATE', 'Certificate / Compliance'), ('OTHER', 'Other')], db_index=True, help_text='Category of governance record. Required for institutional reporting.', max_length=15)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Cooperative-defined governance fields (title, event_date, location, attendees_count, content, document, etc.).')),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governance_records', to='core.cooperative')),
            ],
            options={
                'verbose_name': 'Governance Record',
                'db_table': 'sf_governance',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cooperative', 'record_type'], name='sf_governan_coopera_c071e3_idx')],
            },
        ),
        migrations.CreateModel(
            name='LivestockHealthLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('VACCINATION', 'Vaccination'), ('TREATMENT', 'Medical Treatment'), ('DISEASE', 'Disease Event'), ('ROUTINE_CHECK', 'Routine Check'), ('BIRTH', 'Birth / Calving'), ('DEATH', 'Death'), ('SALE', 'Sale'), ('PURCHASE', 'Purchase'), ('OTHER', 'Other')], db_index=True, help_text='Category of this event. Required — drives vaccination coverage and disease outbreak analytics.', max_length=20)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Cooperative-defined fields (animal_type, event_date, treatment_name, dosage, member, etc.).')),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestock_logs', to='core.cooperative')),
            ],
            options={
                'verbose_name': 'Livestock Health Log',
                'db_table': 'sf_livestock_health',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cooperative', 'event_type'], name='sf_livestoc_coopera_bc610e_idx')],
            },
        ),
        migrations.CreateModel(
            name='MemberHerdRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Cooperative-defined herd fields (animal_type, breed, count, etc.).')),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herd_records', to='core.cooperative')),
                ('member', models.ForeignKey(help_text='The member who owns this herd.', on_delete=django.db.models.deletion.CASCADE, related_name='herd_records', to='core.member')),
            ],
            options={
                'verbose_name': 'Member Herd Record',
                'db_table': 'sf_member_herds',
                'ordering': ['cooperative', 'member'],
                'indexes': [models.Index(fields=['cooperative', 'member'], name='sf_member_h_coopera_4a1b48_idx')],
            },
        ),
        migrations.CreateModel(
            name='MemberLandRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Cooperative-defined land parcel fields (acreage, crop_type, gps, etc.).')),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_records', to='core.cooperative')),
                ('member', models.ForeignKey(help_text='The member who owns or farms this parcel.', on_delete=django.db.models.deletion.CASCADE, related_name='land_records', to='core.member')),
            ],
            options={
                'verbose_name': 'Member Land Record',
                'db_table': 'sf_member_land',
                'ordering': ['cooperative', 'member'],
                'indexes': [models.Index(fields=['cooperative', 'member'], name='sf_member_l_coopera_7834c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_date', models.DateField(db_index=True, help_text='Date of this production event (harvest date, delivery date, etc.). Required — drives time-series capacity analytics.')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Cooperative-defined production fields (product_name, quantity_kg, quality_grade, member, season, etc.).')),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_records', to='core.cooperative')),
            ],
            options={
                'verbose_name': 'Production Record',
                'db_table': 'sf_production_records',
                'ordering': ['-record_date'],
                'indexes': [models.Index(fields=['cooperative', 'record_date'], name='sf_producti_coopera_c86c60_idx')],
            },
        ),
    ]
