# Generated by Django 5.2.11 on 2026-03-05 10:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='helperpermissionoverride',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='helperpermissionoverride',
            name='set_by',
        ),
        migrations.RemoveField(
            model_name='helperpermissionoverride',
            name='user',
        ),
        migrations.RenameField(
            model_name='rolepermission',
            old_name='is_granted',
            new_name='can_create',
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_edit_templates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_view',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('user', 'cooperative', 'module')},
        ),
        migrations.AddField(
            model_name='cooperative',
            name='county',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='physical_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='must_reset_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_2fa_secret',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='two_fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='two_fa_secret',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='cooperative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_permissions', to='core.cooperative'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('MEMBERS', 'Members'), ('PRODUCTION', 'Production'), ('LIVESTOCK', 'Livestock'), ('GOVERNANCE', 'Governance'), ('FINANCE', 'Finance'), ('FORM_BUILDER', 'Form Builder')], max_length=30),
        ),
        migrations.AlterModelTable(
            name='rolepermission',
            table=None,
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=30)),
                ('token', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted', models.BooleanField(default=False)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.cooperative')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_invitations', models.BooleanField(default=True)),
                ('email_tender_updates', models.BooleanField(default=True)),
                ('email_verification_alerts', models.BooleanField(default=True)),
                ('email_system_announcements', models.BooleanField(default=True)),
                ('sms_invitations', models.BooleanField(default=True)),
                ('sms_otp', models.BooleanField(default=True)),
                ('sms_tender_updates', models.BooleanField(default=True)),
                ('sms_critical_alerts', models.BooleanField(default=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='core.cooperative')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'unique_together': {('user', 'cooperative')},
            },
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('REGISTRATION_CERTIFICATE', 'Registration Certificate'), ('TAX_COMPLIANCE', 'Tax Compliance Certificate'), ('AUDITED_ACCOUNTS', 'Audited Accounts'), ('CONSTITUTION', 'Cooperative Constitution'), ('MINUTES_AGM', 'AGM Minutes'), ('OTHER', 'Other Document')], max_length=50)),
                ('file', models.FileField(upload_to='verification/')),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('VERIFIED', 'Verified')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to='core.cooperative')),
            ],
            options={
                'verbose_name': 'Verification Document',
                'verbose_name_plural': 'Verification Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.DeleteModel(
            name='CooperativeInvitation',
        ),
        migrations.DeleteModel(
            name='HelperPermissionOverride',
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='action',
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='role',
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='updated_at',
        ),
    ]
