# Generated by Django 5.2.11 on 2026-03-08 13:16

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_financialrecord_cooperative_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicFieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_model', models.CharField(choices=[('MEMBER', 'Member'), ('PRODUCTION', 'Production Record'), ('LIVESTOCK', 'Livestock Health Log'), ('GOVERNANCE', 'Governance Record'), ('FINANCE', 'Financial Record'), ('LAND', 'Land Record'), ('HERD', 'Herd Record')], help_text="Which model's extra_data column this field lives in.", max_length=15)),
                ('field_key', models.CharField(help_text="Stable snake_case key used as the JSON key in extra_data. Cannot be changed after first submission. Examples: 'irrigation_type', 'coffee_variety', 'hiv_cert_number'.", max_length=100, validators=[core.models._field_key_validator])),
                ('label', models.CharField(help_text='Human-readable display label shown in forms and reports.', max_length=255)),
                ('display_type', models.CharField(choices=[('text', 'Single-line Text'), ('textarea', 'Multi-line Text'), ('number', 'Whole Number'), ('decimal', 'Decimal Number'), ('date', 'Date Picker'), ('datetime', 'Date & Time Picker'), ('dropdown', 'Dropdown (single choice)'), ('multi_select', 'Multi-Select Checkboxes'), ('boolean', 'Yes / No Toggle'), ('file_upload', 'File Upload'), ('image_upload', 'Image Upload'), ('gps', 'GPS Coordinate Picker'), ('rich_text', 'Rich Text (formatted)')], default='text', max_length=15)),
                ('tag', models.CharField(choices=[('CAPACITY', 'Capacity / Production'), ('GOVERNANCE', 'Governance'), ('FINANCIAL', 'Financial'), ('INFORMATIONAL', 'Informational Only')], default='INFORMATIONAL', help_text='Semantic tag — affects Capacity Index computation.', max_length=15)),
                ('help_text_display', models.CharField(blank=True, help_text='Helper text shown below the form input.', max_length=500)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('options', models.JSONField(blank=True, default=list, help_text='["Option A", "Option B"] for dropdown / multi_select fields.')),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text='{"min": 0, "max": 100} or {"max_length": 50} etc.')),
                ('is_required', models.BooleanField(default=False, help_text='If True, submissions that leave this field blank will be rejected. Note: this is a soft constraint enforced by the form, not the DB.')),
                ('is_active', models.BooleanField(default=True, help_text='Soft-delete.  Inactive definitions are hidden from new forms.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_locked', models.BooleanField(default=False, help_text='Set True automatically after the first FormSubmission that uses this field.  field_key cannot be changed once locked.')),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_field_definitions', to='core.cooperative')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dynamic_fields', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dynamic Field Definition',
                'verbose_name_plural': 'Dynamic Field Definitions',
                'db_table': 'sf_dynamic_field_definitions',
                'ordering': ['cooperative', 'target_model', 'label'],
                'indexes': [models.Index(fields=['cooperative', 'target_model', 'is_active'], name='sf_dynamic__coopera_d10b5a_idx')],
                'unique_together': {('cooperative', 'target_model', 'field_key')},
            },
        ),
    ]
