# Generated by Django 5.2.11 on 2026-03-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dynamicfielddefinition'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='is_custom_field',
            field=models.BooleanField(default=False, editable=False, help_text='True if this field maps to a custom key (stored in extra_data). False if it maps to a real model column. Set automatically — cannot be overridden.'),
        ),
    ]
