# Generated by Django 5.2.11 on 2026-03-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_is_custom_field_to_formfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='conditional_rule',
            field=models.JSONField(blank=True, default=dict, help_text='Show/hide this field based on another field\'s value. Format: {"show_if": {"field_id": "<uuid>", "equals": "Maize"}}', null=True),
        ),
    ]
