# Generated by Django 5.2.11 on 2026-03-11 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_allow_null_conditional_rule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.RemoveIndex(
            model_name='member',
            name='sf_members_member__94dab9_idx',
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('cooperative',)},
        ),
        migrations.RemoveField(
            model_name='member',
            name='member_number',
        ),
    ]
