# Generated by Django 5.2.11 on 2026-03-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_member_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['member_number'], 'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='member',
            name='member_number',
            field=models.CharField(default=1, editable=False, help_text='Cooperative-assigned unique member ID. Format is determined by the cooperative (e.g. KAK-001, NK2024001). Auto-generated on member creation.', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('cooperative', 'member_number')},
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['member_number'], name='sf_members_member__94dab9_idx'),
        ),
    ]
