# Generated by Django 5.2.11 on 2026-03-12 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_member_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='gender',
        ),
    ]
