# Generated by Django 5.2.11 on 2026-04-20 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_member_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category", models.CharField(choices=[("ACCOUNT", "Account"), ("INVITATION", "Invitation"), ("TENDER", "Tender"), ("BID", "Bid"), ("VERIFICATION", "Verification"), ("SECURITY", "Security"), ("SYSTEM", "System")], db_index=True, default="SYSTEM", max_length=20)),
                ("event_type", models.CharField(db_index=True, max_length=60)),
                ("priority", models.CharField(choices=[("LOW", "Low"), ("NORMAL", "Normal"), ("HIGH", "High"), ("CRITICAL", "Critical")], default="NORMAL", max_length=10)),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("action_url", models.CharField(blank=True, default="", max_length=500)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("delivery_channels", models.JSONField(blank=True, default=list)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("cooperative", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to="core.cooperative")),
                ("recipient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "sf_notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["recipient", "is_read"], name="sf_notifica_recipie_95c402_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["recipient", "created_at"], name="sf_notifica_recipie_7376c4_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["event_type"], name="sf_notifica_event_t_d2f3b2_idx"),
        ),
    ]
