# Generated by Django 5.2.11 on 2026-04-20 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_notification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='sf_notifica_recipie_d5f4ac_idx',
            old_name='sf_notifica_recipie_95c402_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='sf_notifica_recipie_75fed4_idx',
            old_name='sf_notifica_recipie_7376c4_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='sf_notifica_event_t_9de8ab_idx',
            old_name='sf_notifica_event_t_d2f3b2_idx',
        ),
    ]
