# Generated by Django 5.2.11 on 2026-04-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_rename_sf_notifica_recipie_95c402_idx_sf_notifica_recipie_d5f4ac_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tendermessage",
            name="body",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tendermessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("TEXT", "Text"),
                    ("IMAGE", "Image"),
                    ("VIDEO", "Video"),
                    ("AUDIO", "Audio"),
                    ("DOCUMENT", "Document"),
                ],
                db_index=True,
                default="TEXT",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="tendermessage",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name="tendermessage",
            index=models.Index(
                fields=["tender", "recipient_cooperative"],
                name="sf_tender_m_tender__8e9f1d_idx",
            ),
        ),
    ]
