# Generated by Django 5.2.11 on 2026-04-24 11:30

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_tendermessage_message_type_and_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenderMarketplaceBanner",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "placement",
                    models.CharField(
                        choices=[("COOPERATIVE_DISCOVER", "Cooperative Discover Page")],
                        db_index=True,
                        default="COOPERATIVE_DISCOVER",
                        help_text="Where this promotional banner should appear in the marketplace UI.",
                        max_length=32,
                    ),
                ),
                (
                    "eyebrow",
                    models.CharField(
                        blank=True,
                        help_text="Small label shown above the banner title.",
                        max_length=80,
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Supporting copy that explains the promotion or campaign.",
                    ),
                ),
                (
                    "highlight",
                    models.CharField(
                        blank=True,
                        help_text="Optional proof point, stat, or urgency message.",
                        max_length=120,
                    ),
                ),
                (
                    "surface_theme",
                    models.CharField(
                        choices=[
                            ("CANOPY", "Canopy Green"),
                            ("SUNRISE", "Sunrise Gold"),
                            ("SKYLINE", "Skyline Blue"),
                            ("MIDNIGHT", "Midnight Slate"),
                        ],
                        default="CANOPY",
                        max_length=16,
                    ),
                ),
                ("primary_cta_label", models.CharField(blank=True, max_length=60)),
                (
                    "primary_cta_href",
                    models.CharField(
                        blank=True,
                        help_text="Relative ShambaFlow path or full URL for the primary CTA.",
                        max_length=255,
                    ),
                ),
                ("secondary_cta_label", models.CharField(blank=True, max_length=60)),
                (
                    "secondary_cta_href",
                    models.CharField(
                        blank=True,
                        help_text="Optional secondary CTA link.",
                        max_length=255,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="If false, the banner is hidden even if its schedule is valid.",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional publish start. Leave blank to show immediately.",
                        null=True,
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional publish end. Leave blank to keep showing until disabled.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tender Marketplace Banner",
                "verbose_name_plural": "Tender Marketplace Banners",
                "db_table": "sf_tender_marketplace_banners",
                "ordering": ["placement", "sort_order", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="tendermarketplacebanner",
            index=models.Index(fields=["placement", "is_active"], name="sf_tender_m_placeme_60c0cf_idx"),
        ),
        migrations.AddIndex(
            model_name="tendermarketplacebanner",
            index=models.Index(fields=["starts_at"], name="sf_tender_m_starts__2c8037_idx"),
        ),
        migrations.AddIndex(
            model_name="tendermarketplacebanner",
            index=models.Index(fields=["ends_at"], name="sf_tender_m_ends_at_4f7d5c_idx"),
        ),
    ]
