# Generated by Django 5.2.11 on 2026-04-24 19:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_tendermarketplacebanner"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenderMarketplaceAccessPayment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("SELLAPAY", "SellaPay")],
                        default="SELLAPAY",
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Confirmation"),
                            ("ACTIVE", "Access Granted"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        db_index=True,
                        help_text="Internal reference passed to the payment provider.",
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("amount_kes", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Phone number used for the STK push request.",
                        max_length=20,
                    ),
                ),
                (
                    "normalized_phone",
                    models.CharField(
                        blank=True,
                        help_text="Provider-ready local phone format, e.g. 712345678.",
                        max_length=9,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("provider_transaction_id", models.CharField(blank=True, db_index=True, max_length=80)),
                ("provider_message", models.CharField(blank=True, max_length=255)),
                ("provider_response", models.JSONField(blank=True, default=dict)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("access_expires_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "cooperative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_access_payments",
                        to="core.cooperative",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marketplace_access_payments",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tender Marketplace Access Payment",
                "verbose_name_plural": "Tender Marketplace Access Payments",
                "db_table": "sf_tender_marketplace_access_payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="tendermarketplaceaccesspayment",
            index=models.Index(
                fields=["cooperative", "status"],
                name="sf_tm_access_coop_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tendermarketplaceaccesspayment",
            index=models.Index(
                fields=["cooperative", "access_expires_at"],
                name="sf_tm_access_coop_exp_idx",
            ),
        ),
    ]
